### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by lmohring** [trickyturtle/morkborkFVTT#11]
Tried to install via this URL (maybe that's not the right URL?):
https://raw.githubusercontent.com/trickyturtle/morkborkFVTT/main/system.json

Errors out in Foundry 0.7.9 (after getting to 100% on install) with this message:

> Installation failed: The "path" argument must be of type string. Received type undefined

**Comment by trickyturtle** [comment]
Weird, just tested it and its working fine for me. That is the correct URL. What OS are you using?
I would make sure the system is fully deleted from C:\Users\USERNAME\AppData\Local\FoundryVTT\Data\systems and try again.

**Comment by lmohring** [comment]
Bummer, I hoped it was something easy like wrong URL ;)
I'm on Win10. The system is fully deleted from C:\Users\USERNAME\AppData\Local\FoundryVTT\Data\systems

Probably not be useful, but here's a my browser console error (Firefox):

```
Error: The "path" argument must be of type string. Received type undefined
foundry.js:3614:15
    installPackage http://192.168.56.1:30000/scripts/foundry.js:3614
    _onClickPackageInstall http://192.168.56.1:30000/scripts/foundry.js:23759
    jQuery 2
        dispatch
        handle
```

**Comment by lmohring** [comment]
I figured out what's up -- I am dumb.
I was trying to install via Foundry's "Add-On Modules" tab instead of "Game Systems".
Sorry for wasting your time!

**Comment by trickyturtle** [comment]
Hahaha glad you figured it out. Let me know if you run into anything else
